Bump @sentry/browser from 10.14.0 to 10.15.0 (#3086)
[//]: # (dependabot-start)
⚠️  **Dependabot is rebasing this PR** ⚠️ 

Rebasing might not happen immediately, so don't worry if this takes some
time.

Note: if you make any changes to this PR yourself, they will take
precedence over the rebase.

---

[//]: # (dependabot-end)

Bumps [@sentry/browser](https://github.com/getsentry/sentry-javascript)
from 10.14.0 to 10.15.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/getsentry/sentry-javascript/releases"><code>@​sentry/browser</code>'s
releases</a>.</em></p>
<blockquote>
<h2>10.15.0</h2>
<h3>Important Changes</h3>
<ul>
<li>
<p><strong>feat(cloudflare): Add honoIntegration with error-filtering
function (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17743">#17743</a>)</strong></p>
<p>This release adds a <code>honoIntegration</code> to
<code>@sentry/cloudflare</code>, which exposes a
<code>shouldHandleError</code> function that lets you define which
errors in <code>onError</code> should be captured.
By default, Sentry captures exceptions with <code>error.status &gt;= 500
|| error.status &lt;= 299</code>.</p>
<p>The integration is added by default, and it's possible to modify this
behavior like this:</p>
<pre lang="js"><code> integrations: [
   honoIntegration({
shouldHandleError: (err) =&gt; true; // always capture exceptions in
onError
   })
 ]
</code></pre>
</li>
<li>
<p><strong>feat(node): Add instrumentation for hono handler (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17428">#17428</a>)</strong></p>
</li>
</ul>
<p>This PR enhances the Hono integration by adding comprehensive handler
instrumentation, error handling capabilities.</p>
<ul>
<li>
<p><strong>feat(aws): Enable Lambda extension by default when using the
Lamba layer (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17684">#17684</a>)</strong></p>
</li>
<li>
<p><strong>feat(browser): Add <code>setActiveSpanInBrowser</code> to set
an active span in the browser (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17714">#17714</a>)</strong></p>
</li>
</ul>
<p>This PR adds a feature to the browser SDKs only: Making an inactive
span active. We do this to enable use cases where having a span only
being active in the callback is not practical.</p>
<h3>Other Changes</h3>
<ul>
<li>fix(browser): Improve handling of <code>0</code> and
<code>undefined</code> resource timing values (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17751">#17751</a>)</li>
<li>ref(nextjs): Display build compatibility warning for webpack (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17746">#17746</a>)</li>
</ul>
<!-- raw HTML omitted -->
<ul>
<li>docs: Reword changelog for google gen ai instrumentation (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17753">#17753</a>)</li>
<li>build: Add
<code>@typescript-eslint/no-unnecessary-type-assertion</code> rule (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17728">#17728</a>)</li>
<li>build: Update TS target to <code>es2020</code> everywhere (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17709">#17709</a>)</li>
<li>chore: Add external contributor to CHANGELOG.md (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17745">#17745</a>)</li>
</ul>
<!-- raw HTML omitted -->
<p>Work in this release was contributed by <a
href="https://github.com/Karibash"><code>@​Karibash</code></a>. Thank
you for your contribution!</p>
<h2>Bundle size 📦</h2>
<table>
<thead>
<tr>
<th>Path</th>
<th>Size</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>@​sentry/browser</code></td>
<td>23.69 KB</td>
</tr>
</tbody>
</table>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/getsentry/sentry-javascript/blob/develop/CHANGELOG.md"><code>@​sentry/browser</code>'s
changelog</a>.</em></p>
<blockquote>
<h2>10.15.0</h2>
<h3>Important Changes</h3>
<ul>
<li>
<p><strong>feat(cloudflare): Add honoIntegration with error-filtering
function (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17743">#17743</a>)</strong></p>
<p>This release adds a <code>honoIntegration</code> to
<code>@sentry/cloudflare</code>, which exposes a
<code>shouldHandleError</code> function that lets you define which
errors in <code>onError</code> should be captured.
By default, Sentry captures exceptions with <code>error.status &gt;= 500
|| error.status &lt;= 299</code>.</p>
<p>The integration is added by default, and it's possible to modify this
behavior like this:</p>
<pre lang="js"><code> integrations: [
   honoIntegration({
shouldHandleError: (err) =&gt; true; // always capture exceptions in
onError
   })
 ]
</code></pre>
</li>
<li>
<p><strong>feat(node): Add instrumentation for hono handler (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17428">#17428</a>)</strong></p>
</li>
</ul>
<p>This PR enhances the Hono integration by adding comprehensive handler
instrumentation, error handling capabilities.</p>
<ul>
<li>
<p><strong>feat(aws): Enable Lambda extension by default when using the
Lamba layer (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17684">#17684</a>)</strong></p>
</li>
<li>
<p><strong>feat(browser): Add <code>setActiveSpanInBrowser</code> to set
an active span in the browser (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17714">#17714</a>)</strong></p>
</li>
</ul>
<p>This PR adds a feature to the browser SDKs only: Making an inactive
span active. We do this to enable use cases where having a span only
being active in the callback is not practical.</p>
<h3>Other Changes</h3>
<ul>
<li>fix(browser): Improve handling of <code>0</code> and
<code>undefined</code> resource timing values (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17751">#17751</a>)</li>
<li>ref(nextjs): Display build compatibility warning for webpack (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17746">#17746</a>)</li>
</ul>
<!-- raw HTML omitted -->
<ul>
<li>docs: Reword changelog for google gen ai instrumentation (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17753">#17753</a>)</li>
<li>build: Add
<code>@typescript-eslint/no-unnecessary-type-assertion</code> rule (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17728">#17728</a>)</li>
<li>build: Update TS target to <code>es2020</code> everywhere (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17709">#17709</a>)</li>
<li>chore: Add external contributor to CHANGELOG.md (<a
href="https://redirect.github.com/getsentry/sentry-javascript/pull/17745">#17745</a>)</li>
</ul>
<!-- raw HTML omitted -->
<p>Work in this release was contributed by <a
href="https://github.com/Karibash"><code>@​Karibash</code></a>. Thank
you for your contribution!</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/getsentry/sentry-javascript/commit/d1366f42f242eb9576b30ed305574bf27fdd3396"><code>d1366f4</code></a>
release: 10.15.0</li>
<li><a
href="https://github.com/getsentry/sentry-javascript/commit/2d542340da8a0df1240080567fe3e24d8365bd8b"><code>2d54234</code></a>
Merge pull request <a
href="https://redirect.github.com/getsentry/sentry-javascript/issues/17756">#17756</a>
from getsentry/prepare-release/10.15.0</li>
<li><a
href="https://github.com/getsentry/sentry-javascript/commit/75796c5127d1c94df13a417e189e5e04ca260f8d"><code>75796c5</code></a>
meta(changelog): Update changelog for 10.15.0</li>
<li><a
href="https://github.com/getsentry/sentry-javascript/commit/34538c8d8d24f0fa702a595827e1fb14f55536ab"><code>34538c8</code></a>
feat(cloudflare): Add <code>honoIntegration</code> with error-filtering
function (<a
href="https://redirect.github.com/getsentry/sentry-javascript/issues/17743">#17743</a>)</li>
<li><a
href="https://github.com/getsentry/sentry-javascript/commit/e41942063250a2e735eb36e4cab0f3b93b058b8f"><code>e419420</code></a>
docs: Reword changelog for google gen ai instrumentation (<a
href="https://redirect.github.com/getsentry/sentry-javascript/issues/17753">#17753</a>)</li>
<li><a
href="https://github.com/getsentry/sentry-javascript/commit/105f78ef8056ff1ab616eb92c00cee2a4dc8fd83"><code>105f78e</code></a>
fix(browser): Improve handling of <code>0</code> and
<code>undefined</code> resource timing values ...</li>
<li><a
href="https://github.com/getsentry/sentry-javascript/commit/678d6e81ec4d2be98980fd1150e9f63c8e404e23"><code>678d6e8</code></a>
feat(aws): Enable Lambda extension by default when using the Lamba layer
(<a
href="https://redirect.github.com/getsentry/sentry-javascript/issues/17">#17</a>...</li>
<li><a
href="https://github.com/getsentry/sentry-javascript/commit/c084bd6949b60a1d3b2b9ac8b6340f86e3c84b30"><code>c084bd6</code></a>
ref(nextjs): Display build compatibility warning for webpack (<a
href="https://redirect.github.com/getsentry/sentry-javascript/issues/17746">#17746</a>)</li>
<li><a
href="https://github.com/getsentry/sentry-javascript/commit/16ee36a83ef3cc4ca4d0f682ef9e382d7398d571"><code>16ee36a</code></a>
chore: Add external contributor to CHANGELOG.md (<a
href="https://redirect.github.com/getsentry/sentry-javascript/issues/17745">#17745</a>)</li>
<li><a
href="https://github.com/getsentry/sentry-javascript/commit/01fa69d5f2f39d1c8efa1239891bec021d1247d2"><code>01fa69d</code></a>
feat(node): Add instrumentation for hono handler (<a
href="https://redirect.github.com/getsentry/sentry-javascript/issues/17428">#17428</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/getsentry/sentry-javascript/compare/10.14.0...10.15.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=@sentry/browser&package-manager=npm_and_yarn&previous-version=10.14.0&new-version=10.15.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>